version: '3.9'
services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: /api
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    container_name: travelPhoto-frontend
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
